
dist: trusty
language: node_js
node_js: stable

jobs:
  include:
    - stage: github pages deploy
      node_js: stable
      before_deploy:
      - yarn install
      - yarn build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
