
dist: trusty
language: node_js
node_js: stable

jobs:
  include:
    - stage: install
      script: yarn install
    - stage: build
      script: yarn build
    - stage: deploy:
        - GITHUB_TOKEN=$GITHUB_TOKEN
      script: yarn deploy-storybook:ci
      on:
          branch: master
