dist: trusty
language: node_js
node_js: stable

jobs:
  include:
    - stage: build
      script: yarn build
    - stage: deploy
      if: branch = master
      script: yarn deploy-storybook:ci
      skip-cleanup: true
